import type {Metadata} from "next";
import React from "react";
import Header from "@/components/ContentsLayout/Header";
import Sidebar from "@/components/ContentsLayout/Sidebar";

export const metadata: Metadata = {
    title: "Contents app",
    description: "Generated by create next app",
};
export default function ContentsLayout({
                                           children,
                                       }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className={"w-full h-full flex flex-col "}>
            <Header/>

            <div className={"flex flex-grow overflow-y-auto"}>
                <Sidebar/>
                <main className={"h-full w-full p-3"}>
                    {children}
                </main>

            </div>
            <footer className="bg-gray-200 py-4 text-center text-black">
                Footer
            </footer>

        </div>
    );
}
